-- Supabase Database Schema for Hamza Amirni WhatsApp Bot
-- Copy and paste this script into the SQL Editor of your Supabase Dashboard to create all necessary tables.

-- 1. whatsapp_auth (Stores sessions and databaseSync JSON files)
CREATE TABLE IF NOT EXISTS public.whatsapp_auth (
    phone_number text PRIMARY KEY,
    session_data jsonb,
    pairing_code text,
    status text,
    updated_at timestamp with time zone DEFAULT now()
);

-- 2. bot_configs (Stores Telegram/Facebook bot configurations)
CREATE TABLE IF NOT EXISTS public.bot_configs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    is_active boolean DEFAULT true,
    token text,
    bot_type text,
    username text,
    phone_number text,
    created_at timestamp with time zone DEFAULT now()
);

-- 3. bot_stats (Stores usage statistics and metrics)
CREATE TABLE IF NOT EXISTS public.bot_stats (
    id uuid PRIMARY KEY DEFAULT 'ae6b896b-0b1a-42c2-b5e1-06103b6e82a3'::uuid,
    messages_handled integer DEFAULT 0,
    total_users integer DEFAULT 0,
    ram_usage text DEFAULT '0MB',
    visits integer DEFAULT 0,
    top_commands jsonb DEFAULT '[]'::jsonb,
    last_update timestamp with time zone DEFAULT now()
);

-- 4. ai_memory (Stores Gemini/AI conversation history per user)
CREATE TABLE IF NOT EXISTS public.ai_memory (
    jid text PRIMARY KEY,
    history jsonb DEFAULT '[]'::jsonb,
    last_image text,
    updated_at timestamp with time zone DEFAULT now()
);

-- 5. error_logs (Stores error logging)
CREATE TABLE IF NOT EXISTS public.error_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command text DEFAULT 'unknown',
    error_message text,
    platform text DEFAULT 'WA',
    created_at timestamp with time zone DEFAULT now()
);
